# Website settings
title: "Charlie Chen"
description: "personal website of random stuff I do"
keywords: ""
baseurl: "/"

# author
author:
  name: 'Charlie'
  first_name: 'Charlie'
  last_name: 'Chen'
  email: ''
  facebook_username: ''
  github_username: ''
  linkedin_username: ''

# Build settings
encoding: "utf-8"